### ISSUE TITLE
Add mapPresent and filterPresent to List

### ISSUE THREAD

**Issue by joeseibel** [osate/contract-annex#16]
Add a method to `List` called `mapPresent` that performs a transformation on each element where the transformation returns an optional. Any transformations that result in an empty optional are not included in the resulting list while results that have optionals with values will have those optionals unwrapped and included in the resulting list. For example, if a lambda returns `String?`, then `mapPresent` will return a `List<String>`.

Also add a method to `List` called `filterPresent` that operates on a list of optionals and returns a list with only the non-empty values in it. For example, if a list has the type `List<String?>`, then `filterPresent` will return a `List<String>`.

**Comment by joeseibel** [comment]
Also consider adding a `filterTupleElementsPresent` to `List`. This would operate on a list of tuples and check that each element of a tuple is present in order to pass the filter. The resulting structure would have all of the optionals unwrapped. For example, if a list has the type `List<ComponentInstance?, String, Double?>`, then `filterTupleElementsPresent` would return `List<ComponentInstance, String, Double>`.

**Comment by AaronGreenhouse** [comment]
I agree with this
